config/routes.rb
MovieApp::Application.routes.draw do
  #get "movies/index"
  
  
  root 'movies#index'

  resources :movies

  get 'search', to: 'movies#search'

  #delete to:  'movies#destroy'
#railDELETE /movies/:id(.:format)   to: 'movies#destroy'
  
end

app/models/movie.rb
class Movie < ActiveRecord::Base

 validates :title, :description, :year_released, presence: true
 validates :description, length: { minimum: 3, message: "Your description needs to be at least 4 letters" }
 validates :year_released, numericality: { greater_than_or_equal_to: 1, only_integer: true }
 #validates :numericality { greater_than_or_equal_to: 1, less_than_or_equal_to: 5, only_integer:true }
   

  def self.search_for(query)
      where('title LIKE :query OR description LIKE :query', query: "%#{query}%")
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :find_movie, only: [:update, :edit, :show, :delete]

    def index
      @movies = Movie.all
      
    end

    def new
      @movie = Movie.new 
    end

    def create
      safe_movie = params.require(:movie).permit(:title, :description, :year_released)
      @movie = Movie.new(safe_movie)
      if @movie.save
      redirect_to @movie
      else
      render 'new'
      end
    end


    def search
      query = params[:q]                                                             
      @movies = Movie.search_for(query)
    end
     
    def show
      @movie = Movie.find(params[:id])
    end

    
    def update
      safe_movie = params.require(:movie).permit(:title, :description, :year_released)
      if @movie.update(safe_movie)
      redirect_to @movie
      else
      render 'edit' 
      end
      

    end

    def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
 
    redirect_to index_path
end
      
  

    private

    def safe_movie_params
      params.require(:movie).permit(:title, :descrption, :year_released)
    end 

    def find_movie
      @movie = Movie.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="container">
    <%= yield %>
</div>

</body>
</html>

app/views/movies/_form.html.erb
<% if @movie.errors.any? %>
    <h2>There were errors saving your movie:( </h2>
        <ul>
            <% @movie.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                    <% end %>
        </ul>
<% end %>


<%= form_for @movie do |f| %>
    <fieldset>
        <div class='fields'>
            <%= f.label :title %>
            <%= f.text_field :title %>
        </div>
        <div class= 'fields'>
            <%= f.label :description %>
            <%= f.text_field :description %>
        </div>
        <div class='fields'>
            <%= f.label :year_released %>
            <%= f.text_field :year_released %>
        </div>
    </fieldset>

<%= button_to 'Destroy', edit_movie_path(@movie),
                    method: :delete, data: { confirm: 'Are you sure?' } %>

<%= f.submit %>

<% end %>

app/views/movies/_list.html.erb
<% @movies.each do |movie| %>
   <section>
     <header><%= link_to movie.title, movie %></header>
     <p><%= movie.description %></p>
     <b><%= movie.year_released %></b>
   </section>
  
<% end %>
  

app/views/movies/_search.html.erb
<%= form_tag "/search", method: "GET" do %>
   <%= label_tag :q, "Search" %>
   <%= text_field_tag :q %>
   <%= submit_tag "Search" %>
 <% end %>

app/views/movies/edit.html.erb
<h1>Edit your movie!</h1>
<%= render 'form' %>

app/views/movies/index.html.erb
<h1>Welcome to RetFlix</h1>
<p><%= notice %></p>
<h3><%= link_to "+ Add New Movie", new_movie_path %></h3>

<%= form_tag search_path, method: :get do %>
    <%= text_field_tag :q, nil %>
    <%= submit_tag "Search" %>
<% end %>

<%= render 'list' %>


 

app/views/movies/new.html.erb
<h3><%= link_to "Back to RetFlix", movies_path %></h3>

<h1>Create a new Movie!</h1>

<%= render 'form' %>

app/views/movies/search.html.erb
<h1>Search Results</h1>
<%= render "search" %>
<%= link_to "Back", root_path %>
<%= render "list" %>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>
<p><%= @movie.description %></p>

<%= link_to "Edit", edit_movie_path(@movie) %>